README.adoc

Changed Travis CI badge in README.adoc

---

docs/DeveloperGuide.adoc
docs/OriginalDG.adoc

Added the user stories section and included original DG as OriginalDG.adoc

Developer Guide: User stories

---

docs/DeveloperGuide.adoc

Added Non-Functional Requirements to the DG.

Added NFRs

---

src/main/java/seedu/address/logic/commands/DeleteFlashcardCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/ModelManager.java

Added delete flashcard command

Branch delete flashcard

---

src/main/java/seedu/address/logic/commands/AddCheatSheetCommand.java
src/main/java/seedu/address/logic/commands/DeleteCheatSheetCommand.java
src/main/java/seedu/address/logic/parser/AddCheatSheetCommandParser.java
src/main/java/seedu/address/logic/parser/CheatsheetParserUtil.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyCheatSheetBook.java
src/main/java/seedu/address/model/cheatsheet/exceptions/CheatSheetNotFoundException.java
src/main/java/seedu/address/model/cheatsheet/exceptions/DuplicateCheatSheetException.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java

merged both kb and jasmine work

Merge w kb

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/commands/ListFlashcardCommand.java
src/main/java/seedu/address/model/ReadOnlyFlashcardBook.java
src/main/java/seedu/address/model/UserPrefs.java
src/main/java/seedu/address/storage/AddressBookStorage.java
src/main/java/seedu/address/storage/JsonAddressBookStorage.java
src/main/java/seedu/address/storage/JsonSerializableFlashcardBook.java
src/main/java/seedu/address/storage/JsonStudyBuddyStorage.java
src/main/java/seedu/address/storage/Storage.java
src/main/java/seedu/address/storage/StorageManager.java

@ckb055 how shall we connect the storage? Followed the implementation you used for now :)

Flashcard list GUI & Partially implemented storage

---

src/main/java/seedu/address/logic/commands/AddCheatSheetCommand.java
src/main/java/seedu/address/logic/commands/AddFlashcardCommand.java
src/main/java/seedu/address/logic/commands/EditCheatSheetCommand.java
src/main/java/seedu/address/logic/commands/FilterCheatSheetByTagCommand.java
src/main/java/seedu/address/logic/commands/FilterFlashcardByTagCommand.java
src/main/java/seedu/address/logic/commands/FilterNoteByTagCommand.java
src/main/java/seedu/address/logic/parser/AddCheatSheetCommandParser.java
src/main/java/seedu/address/logic/parser/AddFlashcardCommandParser.java
src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/FilterCheatSheetByTagCommandParser.java
src/main/java/seedu/address/logic/parser/FilterFlashcardByTagCommandParser.java
src/main/java/seedu/address/logic/parser/FilterNoteByTagCommandParser.java
src/main/java/seedu/address/model/cheatsheet/CheatSheet.java
src/main/java/seedu/address/model/cheatsheet/CheatSheetContainsTagPredicate.java
src/main/java/seedu/address/model/cheatsheet/Content.java
src/main/java/seedu/address/model/flashcard/Flashcard.java
src/main/java/seedu/address/model/flashcard/FlashcardContainsTagPredicate.java
src/main/java/seedu/address/model/note/Note.java
src/main/java/seedu/address/model/note/NoteContainsTagPredicate.java
src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
src/test/java/seedu/address/logic/commands/ListNoteCommandTest.java
src/test/java/seedu/address/logic/commands/ViewNoteCommandTest.java
src/test/java/seedu/address/model/note/NoteTest.java
src/test/java/seedu/address/testutil/NoteBuilder.java

- Added the auto-generate feature for cheatsheet
- Standardised the CliSyntax: TITLE, ADDRESS, ANSWER
- Added filters by tag for FLASHCARD, CHEATSHEET and NOTE specifics

Merge integration

---

src/main/java/seedu/address/model/note/Note.java
src/test/java/seedu/address/logic/commands/AddFlashcardCommandTest.java
src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
src/test/java/seedu/address/logic/commands/ListNoteCommandTest.java
src/test/java/seedu/address/logic/commands/ViewNoteCommandTest.java
src/test/java/seedu/address/model/note/NoteTest.java
src/test/java/seedu/address/testutil/NoteBuilder.java
src/test/java/seedu/address/testutil/TypicalNotes.java

Changes:
- Tags can now be used in Notes properly.
- Test cases have been updated to reflect this, except ViewNoteCommandTest.
- Test case for AddFlashcardCommandTest is left commented.

Allow Tags to be used in Notes.

---

src/main/java/seedu/address/logic/commands/cheatsheetcommands/FilterCheatSheetByTagCommand.java
src/main/java/seedu/address/logic/commands/flashcardcommands/FilterFlashcardByTagCommand.java
src/main/java/seedu/address/logic/commands/notecommands/FilterNoteByTagCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/StudyBuddyItem.java
src/main/java/seedu/address/model/UniqueStudyBuddyList.java
src/main/java/seedu/address/model/cheatsheet/CheatSheet.java
src/main/java/seedu/address/model/exceptions/DuplicateStudyBuddyItemException.java
src/main/java/seedu/address/model/exceptions/StudyBuddyItemNotFoundException.java
src/main/java/seedu/address/model/flashcard/Flashcard.java
src/main/java/seedu/address/model/note/Note.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java

Extracting out UniqueStudyBuddyItem list.
And StudyBuddyItem is now a class

Extracting out StudyBuddyItems

---

docs/DeveloperGuide.adoc

Added minor detail in DG

---

docs/UserGuide.adoc

Updated UG

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/cheatsheet/FilterCheatSheetByTagCommand.java
src/main/java/seedu/address/logic/commands/flashcard/FilterFlashcardByTagCommand.java
src/main/java/seedu/address/logic/commands/global/FilterAllByTagCommand.java
src/main/java/seedu/address/logic/commands/note/AddNoteCommand.java
src/main/java/seedu/address/logic/commands/note/FilterNoteByTagCommand.java
src/main/java/seedu/address/logic/parser/FilterAllByTagCommandParser.java
src/main/java/seedu/address/logic/parser/cheatsheet/AddCheatSheetCommandParser.java
src/main/java/seedu/address/logic/parser/cheatsheet/FilterCheatSheetByTagCommandParser.java
src/main/java/seedu/address/logic/parser/flashcard/AddFlashcardCommandParser.java
src/main/java/seedu/address/logic/parser/flashcard/FilterFlashcardByTagCommandParser.java
src/main/java/seedu/address/logic/parser/note/AddNoteCommandParser.java
src/main/java/seedu/address/logic/parser/note/FilterNoteByTagCommandParser.java
src/main/java/seedu/address/model/StudyBuddyItem.java

Added exceptions for tagging

---

docs/DeveloperGuide.adoc
docs/UserGuide.adoc

Added content for time trial implementation in DG (Images not added)
Touched up Flashcard commands in UG

Updated Flashcard segment in UG and DG

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/cheatsheet/AddCheatSheetCommand.java
src/main/java/seedu/address/logic/commands/cheatsheet/DeleteCheatSheetCommand.java
src/main/java/seedu/address/logic/commands/flashcard/AddFlashcardCommand.java
src/main/java/seedu/address/logic/commands/flashcard/DeleteFlashcardCommand.java
src/main/java/seedu/address/logic/commands/note/DeleteNoteCommand.java
src/main/java/seedu/address/model/note/NoteFragmentContainsTagPredicate.java
src/test/java/seedu/address/logic/commands/note/DeleteNoteCommandTest.java

Cheatsheets will now auto-generate from notefragments too.
Added prompts for deletion for all modes.
Can help me test.
Example usage:
delete 2 -> should have prompt
delete 1 -> should still have prompt
delete 2 -> should STILL have prompt
only IF 2 in a row
delete 3 -> have prompt
delete 3 -> successful delete
Help me test if the delete correct also and no bugs! thank you

Updated adding of cheatsheet and prompts for deletion

---

docs/UserGuide.adoc
src/main/java/seedu/address/logic/commands/cheatsheet/AddCheatSheetCommand.java
src/main/java/seedu/address/model/cheatsheet/Content.java

Update UG for deletion prompt
and upon add cheatsheets, will show the amount of content it has pulled

Update UG for deletion prompt and cheatsheet increment

---

docs/UserGuide.adoc

Update UG for v2.0

---

docs/UserGuide.adoc
docs/team/github_ckb055.adoc
docs/team/github_ckb055.pdf
src/main/java/seedu/address/logic/commands/global/ListAllTagsCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/StudyBuddyCounter.java
src/main/java/seedu/address/model/StudyBuddyPro.java
src/test/java/seedu/address/logic/commands/note/AddNoteCommandTest.java
src/test/java/seedu/address/logic/commands/person/AddCommandTest.java

Increment taglist command to be able to provide statistics
Refactored my tagging methods from Model to StudyBuddyPro (makes more sense)
Updated UG accordingly

Increment taglist command

---

docs/DeveloperGuide.adoc
docs/UserGuide.adoc
src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/cheatsheet/DeleteCheatSheetCommand.java
src/main/java/seedu/address/logic/commands/flashcard/DeleteFlashcardCommand.java
src/main/java/seedu/address/logic/commands/note/DeleteNoteCommand.java

As stated
also updated DG UG for that part.

Modified delete prompt such that no longer use exceptions.

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/ui/MainWindow.java

Added startup message

---

src/main/java/seedu/address/model/flashcard/Flashcard.java
src/main/java/seedu/address/model/flashcard/Statistics.java
src/test/java/seedu/address/model/flashcard/FlashcardTest.java
src/test/java/seedu/address/model/flashcard/ScheduleIncrementTest.java
src/test/java/seedu/address/model/flashcard/StatisticsTest.java
src/test/java/seedu/address/model/flashcard/UniqueFlashcardListTest.java

- Improved UniqueFlashcardList tests
- Added tests for ScheduleIncrements and Statistics

Add more Flashcard model tests

---

docs/UserGuide.adoc
src/main/java/seedu/address/logic/commands/flashcard/ShowFlashcardAnswerCommand.java
src/main/java/seedu/address/logic/commands/flashcard/StartTimeTrialCommand.java
src/main/java/seedu/address/logic/commands/flashcard/ViewFlashcardCommand.java
src/main/java/seedu/address/logic/parser/flashcard/StartTimeTrialCommandParser.java
src/main/java/seedu/address/model/flashcard/FlashcardContainsTagPredicate.java
src/main/java/seedu/address/ui/ActivityWindow.java
src/main/java/seedu/address/ui/FlashcardTabWindowController.java
src/main/java/seedu/address/ui/MainWindow.java
src/test/java/seedu/address/logic/parser/flashcard/StartTimeTrialCommandParserTest.java
src/test/java/seedu/address/logic/parser/flashcard/ViewFlashcardCommandParserTest.java

* If a command (other than show) is inputted during the time trial, the time trial will be terminated and the inputted
command will be executed.
* Executing show will reveal the answer of the flashcard in advance, but will not terminate the time trial.

Fixed time trial bugs and updated UG

---

docs/AboutUs.adoc
docs/DeveloperGuide.adoc
docs/UserGuide.adoc

- refactor UG
- changed aboutus link for my PPP (try again)

Refactor UG to standardise the format

---

docs/DeveloperGuide.adoc
docs/SettingUp.adoc
docs/team/chanjunren.adoc
docs/team/ckb055.adoc
docs/templates/_header.html.slim
docs/tutorials/RemovingFields.adoc

- Edited the headers of the website (hope it works)
- Manually edited my PPP for (../stylesheets)
- Edited all other teammates gradlew problem

fixed the warnings of gradlew

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/model/util/SampleDataUtil.java

Fixed taglist bug

---

docs/UserGuide.adoc

Fix small typo in png

---

docs/DeveloperGuide.adoc

Edit use cases.
